### ISSUE TITLE
basic logic blocks.

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#1]
if else, switch etc statements as blocks you can put actions into then or code into.

**Comment by erickwatson** [comment]
The way MixItUp handles this works best for me, having the "Conditionals" logic is more user friendly than they way SB handles If/Else and then breaks.
![image](https://user-images.githubusercontent.com/30871379/230013399-43ee2103-485f-4c6f-8856-906c45d50b8f.png)

**Comment by Brendonovich** [comment]
irrelevant now bc graph and `Branch`
