### ISSUE TITLE
Dropdown as an input option for set lists of inputs.

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#110]
Perfect example is the update redemption status node. The status option could have "CANCELLED" or "FULFILLED" as the two options you can pick from on the drop down. 
![image](https://github.com/Brendonovich/macrograph/assets/51935420/32c49fe0-04c9-4925-8015-b12c9af695ef)

**Comment by Brendonovich** [comment]
aka enums
