### ISSUE TITLE
to json doesnt work on plain old  arrays. 

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#167]
will just print out [null.null,null,null,null] etc. instead of the actual values of the array.

repro graph: eyJpZCI6NywibmFtZSI6IkdyYXBoIDciLCJub2RlSWRDb3VudGVyIjo2LCJub2RlcyI6eyIxIjp7ImlkIjoxLCJuYW1lIjoiU3BsaXQgU3RyaW5nIiwicG9zaXRpb24iOnsieCI6ODMyLCJ5Ijo1MzJ9LCJzY2hlbWEiOnsicGFja2FnZSI6IlV0aWxzIiwiaWQiOiJTcGxpdCBTdHJpbmcifSwiZGVmYXVsdFZhbHVlcyI6eyJpbnB1dCI6IjEgMiAzIDQgNSA2IDcgOCA5Iiwic2VwYXJhdG9yIjoiICJ9fSwiMiI6eyJpZCI6MiwibmFtZSI6IlRvIEpTT04iLCJwb3NpdGlvbiI6eyJ4IjoxMDY3LCJ5Ijo1NDh9LCJzY2hlbWEiOnsicGFja2FnZSI6IkpTT04iLCJpZCI6IlRvIEpTT04ifSwiZGVmYXVsdFZhbHVlcyI6eyJpbiI6eyJ2YWx1ZSI6bnVsbH19fSwiMyI6eyJpZCI6MywibmFtZSI6IlN0cmluZ2lmeSBKU09OIiwicG9zaXRpb24iOnsieCI6MTE3MywieSI6NTA5fSwic2NoZW1hIjp7InBhY2thZ2UiOiJVdGlscyIsImlkIjoiU3RyaW5naWZ5IEpTT04ifSwiZGVmYXVsdFZhbHVlcyI6eyJpbiI6eyJ2YXJpYW50IjoiTnVsbCJ9fX0sIjQiOnsiaWQiOjQsIm5hbWUiOiJBIEtleSIsInBvc2l0aW9uIjp7IngiOjk3NywieSI6MzgzfSwic2NoZW1hIjp7InBhY2thZ2UiOiJLZXlib2FyZCBJbnB1dHMiLCJpZCI6IkEgS2V5In0sImRlZmF1bHRWYWx1ZXMiOnt9fSwiNSI6eyJpZCI6NSwibmFtZSI6IlByaW50IiwicG9zaXRpb24iOnsieCI6MTQzOSwieSI6NDk0fSwic2NoZW1hIjp7InBhY2thZ2UiOiJVdGlscyIsImlkIjoiUHJpbnQifSwiZGVmYXVsdFZhbHVlcyI6eyJpbnB1dCI6IiJ9fX0sImNvbW1lbnRCb3hlcyI6W10sImNvbm5lY3Rpb25zIjpbeyJmcm9tIjp7Im5vZGUiOjEsIm91dHB1dCI6Im91dHB1dCJ9LCJ0byI6eyJub2RlIjoyLCJpbnB1dCI6ImluIn19LHsiZnJvbSI6eyJub2RlIjo0LCJvdXRwdXQiOiJwcmVzc2VkIn0sInRvIjp7Im5vZGUiOjMsImlucHV0IjoiZXhlYyJ9fSx7ImZyb20iOnsibm9kZSI6Miwib3V0cHV0Ijoib3V0In0sInRvIjp7Im5vZGUiOjMsImlucHV0IjoiaW4ifX0seyJmcm9tIjp7Im5vZGUiOjMsIm91dHB1dCI6ImV4ZWMifSwidG8iOnsibm9kZSI6NSwiaW5wdXQiOiJleGVjIn19LHsiZnJvbSI6eyJub2RlIjozLCJvdXRwdXQiOiJzdHJpbmcifSwidG8iOnsibm9kZSI6NSwiaW5wdXQiOiJpbnB1dCJ9fV19

**Comment by Brendonovich** [comment]
Fixed
