### ISSUE TITLE
Exec bugs out when connecting multiple nodes to the same node.

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#252]
Connect 3 nodes in this orientation.

![image](https://github.com/Brendonovich/macrograph/assets/51935420/17e6d5d3-9250-444e-837a-812757fbd018)

Double click on the input for the right side node and this happens.

![image](https://github.com/Brendonovich/macrograph/assets/51935420/c027b192-5763-46d4-ad5b-2885bfdab468)

Also connecting like this shouldnt be possible. exec doesnt actually flow the UI is just wrong.

![image](https://github.com/Brendonovich/macrograph/assets/51935420/f542c8e7-6407-469e-bde3-651b42ea7577)

**Comment by Brendonovich** [comment]
[5fa3b87](https://github.com/Brendonovich/macrograph/commit/5fa3b87fe3e0def970682abdc66d5c3620e4a690) makes these combinations illegal
