### ISSUE TITLE
Custom Structs

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#280]

**Comment by jdudetv** [comment]
Custom structs are bugged

**Comment by Hannah-GBS** [comment]
> Custom structs are bugged

Reloading voids the contents of inputs on the node itself
https://macrograph.brendonovich.dev/playground?shared=86ccd1cc-f5f5-4a95-9bab-3177676904e5

**Comment by Brendonovich** [comment]
creating a field when a variable of a custom struct already exists causes `serializeValue` to fail to locate the field's data, so we need to add a default in transparently while serializing.
