### ISSUE TITLE
Map<Map<String>> wildcard doesn't propagate properly

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/MacroGraph#315]
```
eyJ0eXBlIjoicHJvamVjdCIsInByb2plY3QiOnsiZ3JhcGhJZENvdW50ZXIiOjEyLCJncmFwaHMiOlt7ImlkIjoxMSwibmFtZSI6IkdyYXBoIDExIiwibm9kZUlkQ291bnRlciI6MTQsIm5vZGVzIjp7IjkiOnsiaWQiOjksIm5hbWUiOiJNYXAgR2V0IiwicG9zaXRpb24iOnsieCI6NzI1LCJ5Ijo1MDB9LCJzY2hlbWEiOnsicGFja2FnZSI6Ik1hcCIsImlkIjoiTWFwIEdldCJ9LCJkZWZhdWx0VmFsdWVzIjp7Im1hcCI6bnVsbCwia2V5LTAiOiIifSwicHJvcGVydGllcyI6eyJudW1iZXIiOjF9fSwiMTAiOnsiaWQiOjEwLCJuYW1lIjoiVW53cmFwIE9wdGlvbiIsInBvc2l0aW9uIjp7IngiOjg4Ny44NjE0MjM4NzAyOTkyLCJ5Ijo0OTkuODU1ODA2NTg4NDc2ODd9LCJzY2hlbWEiOnsicGFja2FnZSI6IlV0aWxzIiwiaWQiOiJVbndyYXAgT3B0aW9uIn0sImRlZmF1bHRWYWx1ZXMiOnsiaW5wdXQiOm51bGx9LCJwcm9wZXJ0aWVzIjp7fX0sIjEzIjp7ImlkIjoxMywibmFtZSI6IkdldCBHcmFwaCBWYXJpYWJsZSIsInBvc2l0aW9uIjp7IngiOjU3NSwieSI6NTAwfSwic2NoZW1hIjp7InBhY2thZ2UiOiJWYXJpYWJsZXMiLCJpZCI6IkdldCBHcmFwaCBWYXJpYWJsZSJ9LCJkZWZhdWx0VmFsdWVzIjp7fSwicHJvcGVydGllcyI6eyJ2YXJpYWJsZSI6Mn19fSwiY29tbWVudEJveGVzIjpbXSwidmFyaWFibGVzIjpbeyJpZCI6MiwibmFtZSI6IlZhcmlhYmxlIDEiLCJ2YWx1ZSI6e30sInR5cGUiOnsidmFyaWFudCI6Im1hcCIsInZhbHVlIjp7InZhcmlhbnQiOiJtYXAiLCJ2YWx1ZSI6InN0cmluZyJ9fX0seyJpZCI6MywibmFtZSI6IlZhcmlhYmxlIDIiLCJ2YWx1ZSI6MCwidHlwZSI6InN0cmluZyJ9XSwiY29ubmVjdGlvbnMiOlt7ImZyb20iOnsibm9kZSI6MTMsIm91dHB1dCI6IiJ9LCJ0byI6eyJub2RlIjo5LCJpbnB1dCI6Im1hcCJ9fSx7ImZyb20iOnsibm9kZSI6OSwib3V0cHV0IjoidmFsdWUtMCJ9LCJ0byI6eyJub2RlIjoxMCwiaW5wdXQiOiJpbnB1dCJ9fV19XSwiY3VzdG9tRXZlbnRJZENvdW50ZXIiOjIsImN1c3RvbUV2ZW50cyI6W3siaWQiOjAsIm5hbWUiOiJFdmVudCAwIiwiZmllbGRzIjpbeyJpZCI6MCwibmFtZSI6IlBpbiAwIiwidHlwZSI6InN0cmluZyJ9LHsiaWQiOjEsIm5hbWUiOiJQaW4gMSIsInR5cGUiOiJzdHJpbmcifSx7ImlkIjoyLCJuYW1lIjoiUGluIDIiLCJ0eXBlIjoic3RyaW5nIn1dLCJmaWVsZElkQ291bnRlciI6M31dLCJjb3VudGVyIjowLCJyZXNvdXJjZXMiOltdfX0=
```

**Comment by jdudetv** [comment]
repro with match / break scope nodes too :
eyJ0eXBlIjoiZ3JhcGgiLCJncmFwaCI6eyJpZCI6MTUyLCJuYW1lIjoiTWF0Y2ggQnJlYWsgc2NvcGUgYWxzbyBicm9rZW4iLCJub2RlSWRDb3VudGVyIjo0NSwibm9kZXMiOnsiMzAiOnsiaWQiOjMwLCJuYW1lIjoiSyBLZXkiLCJwb3NpdGlvbiI6eyJ4Ijo2MjUsInkiOi0zNzV9LCJzY2hlbWEiOnsicGFja2FnZSI6IktleWJvYXJkIElucHV0cyIsImlkIjoiSyBLZXkifSwiZGVmYXVsdFZhbHVlcyI6e30sInByb3BlcnRpZXMiOnt9fSwiMzQiOnsiaWQiOjM0LCJuYW1lIjoiR2V0IEdyYXBoIFZhcmlhYmxlIiwicG9zaXRpb24iOnsieCI6NDAwLCJ5IjotMTUwfSwic2NoZW1hIjp7InBhY2thZ2UiOiJWYXJpYWJsZXMiLCJpZCI6IkdldCBHcmFwaCBWYXJpYWJsZSJ9LCJkZWZhdWx0VmFsdWVzIjp7fSwicHJvcGVydGllcyI6eyJ2YXJpYWJsZSI6MjV9fSwiMzUiOnsiaWQiOjM1LCJuYW1lIjoiTWFwIEdldCIsInBvc2l0aW9uIjp7IngiOjYyNSwieSI6LTIyNX0sInNjaGVtYSI6eyJwYWNrYWdlIjoiTWFwIiwiaWQiOiJNYXAgR2V0In0sImRlZmF1bHRWYWx1ZXMiOnsibWFwIjpudWxsLCJrZXktMCI6InRlc3QifSwicHJvcGVydGllcyI6eyJudW1iZXIiOjF9fSwiMzYiOnsiaWQiOjM2LCJuYW1lIjoiTWF0Y2giLCJwb3NpdGlvbiI6eyJ4Ijo4NTAsInkiOi0zNzV9LCJzY2hlbWEiOnsicGFja2FnZSI6IlV0aWxzIiwiaWQiOiJNYXRjaCJ9LCJkZWZhdWx0VmFsdWVzIjp7ImRhdGEiOm51bGx9LCJwcm9wZXJ0aWVzIjp7fX0sIjM3Ijp7ImlkIjozNywibmFtZSI6IkJyZWFrIFNjb3BlIiwicG9zaXRpb24iOnsieCI6MTAwMCwieSI6LTM3NX0sInNjaGVtYSI6eyJwYWNrYWdlIjoiVXRpbHMiLCJpZCI6IkJyZWFrIFNjb3BlIn0sImRlZmF1bHRWYWx1ZXMiOnt9LCJwcm9wZXJ0aWVzIjp7fX0sIjM4Ijp7ImlkIjozOCwibmFtZSI6Ik1hcCBHZXQiLCJwb3NpdGlvbiI6eyJ4IjoxMTAwLCJ5IjotMjUwfSwic2NoZW1hIjp7InBhY2thZ2UiOiJNYXAiLCJpZCI6Ik1hcCBHZXQifSwiZGVmYXVsdFZhbHVlcyI6eyJtYXAiOm51bGwsImtleS0wIjoiMiJ9LCJwcm9wZXJ0aWVzIjp7Im51bWJlciI6MX19LCIzOSI6eyJpZCI6MzksIm5hbWUiOiJNYXRjaCIsInBvc2l0aW9uIjp7IngiOjEyNzUsInkiOi0zNzV9LCJzY2hlbWEiOnsicGFja2FnZSI6IlV0aWxzIiwiaWQiOiJNYXRjaCJ9LCJkZWZhdWx0VmFsdWVzIjp7ImRhdGEiOm51bGx9LCJwcm9wZXJ0aWVzIjp7fX0sIjQwIjp7ImlkIjo0MCwibmFtZSI6IkJyZWFrIFNjb3BlIiwicG9zaXRpb24iOnsieCI6MTQyNSwieSI6LTM3NX0sInNjaGVtYSI6eyJwYWNrYWdlIjoiVXRpbHMiLCJpZCI6IkJyZWFrIFNjb3BlIn0sImRlZmF1bHRWYWx1ZXMiOnt9LCJwcm9wZXJ0aWVzIjp7fX0sIjQxIjp7ImlkIjo0MSwibmFtZSI6IkdldCBMaXN0IFZhbHVlIiwicG9zaXRpb24iOnsieCI6MTU1MCwieSI6LTI1MH0sInNjaGVtYSI6eyJwYWNrYWdlIjoiTGlzdCIsImlkIjoiR2V0IExpc3QgVmFsdWUifSwiZGVmYXVsdFZhbHVlcyI6eyJsaXN0IjpudWxsLCJpbmRleCI6MH0sInByb3BlcnRpZXMiOnt9fSwiNDIiOnsiaWQiOjQyLCJuYW1lIjoiTWF0Y2giLCJwb3NpdGlvbiI6eyJ4IjoxNzUwLCJ5IjotMzUwfSwic2NoZW1hIjp7InBhY2thZ2UiOiJVdGlscyIsImlkIjoiTWF0Y2gifSwiZGVmYXVsdFZhbHVlcyI6eyJkYXRhIjpudWxsfSwicHJvcGVydGllcyI6e319LCI0MyI6eyJpZCI6NDMsIm5hbWUiOiJCcmVhayBTY29wZSIsInBvc2l0aW9uIjp7IngiOjE5MDAsInkiOi0zNTB9LCJzY2hlbWEiOnsicGFja2FnZSI6IlV0aWxzIiwiaWQiOiJCcmVhayBTY29wZSJ9LCJkZWZhdWx0VmFsdWVzIjp7fSwicHJvcGVydGllcyI6e319LCI0NCI6eyJpZCI6NDQsIm5hbWUiOiJQcmludCIsInBvc2l0aW9uIjp7IngiOjIwMDAsInkiOi0zNTB9LCJzY2hlbWEiOnsicGFja2FnZSI6IlV0aWxzIiwiaWQiOiJQcmludCJ9LCJkZWZhdWx0VmFsdWVzIjp7ImlucHV0IjoiIn0sInByb3BlcnRpZXMiOnt9fX0sImNvbW1lbnRCb3hlcyI6W10sInZhcmlhYmxlcyI6W3siaWQiOjI1LCJuYW1lIjoiVmFyaWFibGUgMSIsInZhbHVlIjp7InRlc3QiOnsiMiI6WyIzIl19fSwidHlwZSI6eyJ2YXJpYW50IjoibWFwIiwidmFsdWUiOnsidmFyaWFudCI6Im1hcCIsInZhbHVlIjp7InZhcmlhbnQiOiJsaXN0IiwiaXRlbSI6InN0cmluZyJ9fX19XSwiY29ubmVjdGlvbnMiOlt7ImZyb20iOnsibm9kZSI6MTEsIm91dHB1dCI6IkFubm91bmNtZW50In0sInRvIjp7Im5vZGUiOjEyLCJpbnB1dCI6IiJ9fSx7ImZyb20iOnsibm9kZSI6MzQsIm91dHB1dCI6IiJ9LCJ0byI6eyJub2RlIjozNSwiaW5wdXQiOiJtYXAifX0seyJmcm9tIjp7Im5vZGUiOjM1LCJvdXRwdXQiOiJ2YWx1ZS0wIn0sInRvIjp7Im5vZGUiOjM2LCJpbnB1dCI6ImRhdGEifX0seyJmcm9tIjp7Im5vZGUiOjM2LCJvdXRwdXQiOiJzb21lIn0sInRvIjp7Im5vZGUiOjM3LCJpbnB1dCI6IiJ9fSx7ImZyb20iOnsibm9kZSI6MzcsIm91dHB1dCI6InZhbHVlIn0sInRvIjp7Im5vZGUiOjM4LCJpbnB1dCI6Im1hcCJ9fSx7ImZyb20iOnsibm9kZSI6MzgsIm91dHB1dCI6InZhbHVlLTAifSwidG8iOnsibm9kZSI6MzksImlucHV0IjoiZGF0YSJ9fSx7ImZyb20iOnsibm9kZSI6MzksIm91dHB1dCI6InNvbWUifSwidG8iOnsibm9kZSI6NDAsImlucHV0IjoiIn19LHsiZnJvbSI6eyJub2RlIjozNywib3V0cHV0IjoiIn0sInRvIjp7Im5vZGUiOjM5LCJpbnB1dCI6ImV4ZWMifX0seyJmcm9tIjp7Im5vZGUiOjQwLCJvdXRwdXQiOiJ2YWx1ZSJ9LCJ0byI6eyJub2RlIjo0MSwiaW5wdXQiOiJsaXN0In19LHsiZnJvbSI6eyJub2RlIjo0MSwib3V0cHV0IjoicmV0dXJuIn0sInRvIjp7Im5vZGUiOjQyLCJpbnB1dCI6ImRhdGEifX0seyJmcm9tIjp7Im5vZGUiOjQyLCJvdXRwdXQiOiJzb21lIn0sInRvIjp7Im5vZGUiOjQzLCJpbnB1dCI6IiJ9fSx7ImZyb20iOnsibm9kZSI6NDAsIm91dHB1dCI6IiJ9LCJ0byI6eyJub2RlIjo0MiwiaW5wdXQiOiJleGVjIn19LHsiZnJvbSI6eyJub2RlIjo0Mywib3V0cHV0IjoidmFsdWUifSwidG8iOnsibm9kZSI6NDQsImlucHV0IjoiaW5wdXQifX0seyJmcm9tIjp7Im5vZGUiOjQzLCJvdXRwdXQiOiIifSwidG8iOnsibm9kZSI6NDQsImlucHV0IjoiZXhlYyJ9fSx7ImZyb20iOnsibm9kZSI6MzAsIm91dHB1dCI6InByZXNzZWQifSwidG8iOnsibm9kZSI6MzYsImlucHV0IjoiZXhlYyJ9fV19fQ==
