### ISSUE TITLE
allow for re-ordering UI elements, re-order graphs, re-order variables, custom events etc.

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#320]

**Comment by Brendonovich** [comment]
![image](https://github.com/Brendonovich/macrograph/assets/14191578/6f892340-8d09-42ce-9165-f20d1e2fcd37)

**Comment by jdudetv** [comment]
![remix-a6296f75-8293-4268-b846-f4000190853d](https://github.com/Brendonovich/macrograph/assets/51935420/56018fa5-9f83-4188-a149-8788fb1768cd)

**Comment by Brendonovich** [comment]
search >>>
