### ISSUE TITLE
Webview update broke zooming on windows chromium based web and desktop app

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#389]
Webview updated and broke zooming on windows. Works in firefox on windows and works on safari. 

The onWheel event just doesnt emit anymore.

**Comment by jdudetv** [comment]
app Works: MAC OS
app Doesnt work: Windows 10, windows 11

web works: Safari, Firefox
web Doesnt Work: Chrome, Brave, Edge

**Comment by Brendonovich** [comment]
fixed in 9dc87eef9ed9
