### ISSUE TITLE
JSON Match doesnt contain struct data. Need a from JSON node to get the data back out.

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#401]

**Comment by jdudetv** [comment]
![image](https://github.com/Brendonovich/macrograph/assets/51935420/3108b455-9c95-4a5d-b088-fa934accf3c4)

**Comment by Brendonovich** [comment]
This is intentional, i think you're looking for a 'From JSON' node

**Comment by Brendonovich** [comment]
Implemented a basic version that doesn't do validation
