### ISSUE TITLE
Don't open the node suggestion menu if the connection is released over an existing node

### ISSUE THREAD

**Issue by Hannah-GBS** [Brendonovich/MacroGraph#418]
Just consume it or something idk, or keep the behaviour where after releasing click you can click the place you meant to (see second video), but without opening the suggestion menu

https://github.com/user-attachments/assets/3ca46e0a-0c6c-476a-93b6-a443ab12ee19

https://github.com/user-attachments/assets/845a3486-fc99-4e8c-81fe-48595b214ea2

**Comment by Brendonovich** [comment]
closed by 5e160ced5c1e
