### ISSUE TITLE
Deleting comment boxes broken

### ISSUE THREAD

**Issue by oscartbeaumont** [Brendonovich/MacroGraph#423]
Using the delete key on the keyboard when the header bar is focused.

**Comment by oscartbeaumont** [comment]
This seems to only be a problem on desktop. Works fine on web.

**Comment by Brendonovich** [comment]
no idea why this happens, need to make a better keyboard shortcuts system

**Comment by Brendonovich** [comment]
fixed in 3152594b8f60
