### ISSUE TITLE
wildcard issues

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/MacroGraph#435]
repro: https://macrograph.brendonovich.dev/playground?shared=c816e657-e9d0-4c20-a6fa-5d47f9576f59

**Comment by jdudetv** [comment]
another repro: [https://macrograph.brendonovich.dev/playground?shared=fb0389f8-153b-429f-907c-187d4a907bc0](https://macrograph.brendonovich.dev/playground?shared=fb0389f8-153b-429f-907c-187d4a907bc0)

**Comment by Hannah-GBS** [comment]
anotha one: [https://macrograph.brendonovich.dev/playground?shared=58735705-91ff-4aad-a6e8-3786c71c8de8](https://macrograph.brendonovich.dev/playground?shared=58735705-91ff-4aad-a6e8-3786c71c8de8)

**Comment by Brendonovich** [comment]
ad10df18327c
