### ISSUE TITLE
Adding Twitch credential fails; `window.opener` is null

### ISSUE THREAD

**Issue by iLynxcat** [Brendonovich/MacroGraph#467]
On the production deployment (macrograph.brendonovich.dev) adding a Twitch credential simply loads a blank page on the callback.

![Safari window displaying a blank white page](https://github.com/user-attachments/assets/1c9c4454-d008-4847-88d8-25f825643643)

Digging deeper, I saw an error in the JavaScript console:

```
TypeError: null is not an object (evaluating 'opener.postMessage') (callback:5)
```

So I created a response override (best Safari devtools feature btw) with a debugger statement and moved some things into variables to inspect:

```javascript
<script data-hk=0 data-target-origin="https://macrograph.brendonovich.dev">
const targetOrigin = document.currentScript.getAttribute("data-target-origin");

const opener = window.opener; // null
const postMessage = opener?.postMessage; // undefined
const search = location.search; // string (expected value)
debugger;
opener.postMessage(location.search, targetOrigin);
window.close();
</script>
```

**Comment by iLynxcat** [comment]
Don't know if this is a Safari behavior blocking access to the opener? Either way I wonder if this warrants using a different system for sending this message to the server

**Comment by iLynxcat** [comment]
On further attempts, it does properly close itself but the second Twitch account doesn't display within the credentials page. Are multiple credentials unsupported and it's simply not showing anything?

**Comment by jdudetv** [comment]
multiple credentials are supported this is super strange will have brendo have a look into it as he's on mac.

**Comment by iLynxcat** [comment]
that's what I thought, weird bug. I am on macOS 15 beta so that could affect it, can try it in my Sonoma 14.6 VM in a bit and see if it repros

**Comment by Brendonovich** [comment]
safari login & twitch auth should work properly now

**Comment by iLynxcat** [comment]
issue does still happen when popup is blocked and you manually open it, but after you allow and try again safari attaches window.opener fine
