### ISSUE TITLE
drag to select: select if node is mostly covered

### ISSUE THREAD

**Issue by iLynxcat** [Brendonovich/MacroGraph#481]
not sure what the amount of coverage should be but 100% isn't enough:

in this example, I started the selection from the opposite corner of the Chat Message node but missed it by a few pixels at the bottom. it should select chat message since it's at such a massive coverage of the area of the node even though it's not 100%.

https://github.com/user-attachments/assets/620f789b-daa3-47b5-9b43-b9a905224154

not sure if selecting when the area covers even the tiniest bit is a better solution, lots of accidental selections would likely happen that way

**Comment by jdudetv** [comment]
I think a compromise would be using a bounding box that's like inset from the edge of the node so like 10% smaller around the edge so small edge cases like this get selected. But also I like the current behaviour as you can be very precise in what you want and don't want selected when nodes are overlapped

**Comment by iLynxcat** [comment]
agree i like that idea
