### ISSUE TITLE
magnetic snapping doesn't highlight target connection point

### ISSUE THREAD

**Issue by iLynxcat** [Brendonovich/MacroGraph#484]
when magnetically snapping a connector, the target connection point does not highlight unless you are hovering directly over it

**Comment by Brendonovich** [comment]
I don't think I want the target pin to look like it's connected when it's not, but there could be a separate indicator like a ring around the pin

**Comment by iLynxcat** [comment]
maybe so -- atm I just expected it to mirror what happens without magnetic snapping: when you mouseover the pin to form a connection the pin fills in

**Comment by Brendonovich** [comment]
damn you right
